### ISSUE TITLE
Increase default PSQL version

### ISSUE THREAD

**Issue by sbesson** [ome/devspace#180]
Makes sense & +1 for keeping things in sync. Can certainly see an upcoming round of bumping to 12 if not 13 across the board.

_Originally posted by @joshmoore in https://github.com/ome/devspace/issues/179#issuecomment-756639809_

From https://docs.openmicroscopy.org/omero/5.6.2/sysadmins/version-requirements.html#postgresql, bumping at least to PSQL 11 would be inline with our recommended version. No objection to testing with 12 and/or 13 in the CI environment.

**Comment by joshmoore** [comment]
Other locations I can think of:
 - omero-test-infra
 - example docker-compose
 - ansible roles
 - ansible playbooks (?)
 - production servers

**Comment by sbesson** [comment]
I was looking at that separately. A quick audit of https://github.com/search?l=YAML&p=2&q=org%3Aome+image%3A+%5C%22postgres&type=Code and https://github.com/search?l=YAML&q=org%3Aome+%22postgresql_version%3A%22&type=Code suggests many places have been bumped to 11 at least.

A few candidates for bumping:

- https://github.com/ome/omero-test-infra/blob/fedbaf58bdd93d112f8918df91c7d5c3562ace07/.env#L5
- https://github.com/ome/prod-playbooks/blob/a27d6208921a74ff2628f13ea473acbc798a2bab/k8s/postgres/playbook.yml
- https://github.com/ome/prod-playbooks/blob/934f499311c17f2285d48163498576ff2e9b3ccc/sls-gallery.yml
- https://github.com/ome/prod-playbooks/blob/a27d6208921a74ff2628f13ea473acbc798a2bab/learning.yml
- https://github.com/ome/prod-playbooks/blob/38a95488a85e5e6e202532876a4a4299bb498a23/omero/training-server/playbook.yml

**Comment by jburel** [comment]
we are now running psql 16
