### ISSUE TITLE
Default nexus admin password

### ISSUE THREAD

**Issue by sbesson** [ome/devspace#182]
See https://github.com/sonatype/docker-nexus3/commit/bd57ceec2a0f374f1c2a112177186ab7a949e8bf

Recreating the nexus service (likely after repulling) led to issues when trying to authenticate to populate the repository. While the password was previously assumed to be `admin123` (and hardcoded in the script), I retrieved it by shelling into the container and reading the content of `admin.password`.

Either we can include some logic to read this password and pass it to the initialization script or we could try and override it, possibly by creating a custom `admin.password` file under `nexus-data`

**Comment by joshmoore** [comment]
Aha. So newer images have changed the behavior, no?

**Comment by sbesson** [comment]
Yes (likely for security reasons)

**Comment by manics** [comment]
Looks like I ran into that new password behaviour in https://github.com/ome/devspace/pull/159

**Comment by jburel** [comment]
https://github.com/ome/devspace/pull/206 avoid the creation of random password
