### ISSUE TITLE
Devspace landing page

### ISSUE THREAD

**Issue by joshmoore** [ome/devspace#79]
A user coming to a devspace must currently know a number of URLs (possibly with varying ports) that can be confusing. A single landing page could be generated with the necessary information.

**Comment by sbesson** [comment]
Since at least one dynamic port (probably the `nginxjenkins 443` one) will need to be known, one possibility I can think of would be to generate a Jenkins [user content](https://wiki.jenkins.io/display/JENKINS/User+Content) readme/landing page i.e. https://$DOCKERHOST:$JENKINSPORT/userContent

**Comment by jburel** [comment]
I have updated the readme with the various informations and how to retrieve the ports
Also it is no longer necessary to go to infrastructure to run the playbooks
